//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHArK.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHArK.Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SHArK....
        /// </summary>
        public static string AboutSHArK {
            get {
                return ResourceManager.GetString("AboutSHArK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the SHArK Application.
        /// </summary>
        public static string AboutSHArKScreenTipDesc {
            get {
                return ResourceManager.GetString("AboutSHArKScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SHArK.
        /// </summary>
        public static string AboutSHArKTitle {
            get {
                return ResourceManager.GetString("AboutSHArKTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHArK Scanning Station.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoscale Axes.
        /// </summary>
        public static string AutoscaleAxes {
            get {
                return ResourceManager.GetString("AutoscaleAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Autoscale.png.
        /// </summary>
        public static string AutoscaleAxesImageSource {
            get {
                return ResourceManager.GetString("AutoscaleAxesImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the X- and Y-Axes to fit the content of the Spectrum.
        /// </summary>
        public static string AutoscaleAxesScreenTipDesc {
            get {
                return ResourceManager.GetString("AutoscaleAxesScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes.
        /// </summary>
        public static string Axes {
            get {
                return ResourceManager.GetString("Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/BasicLogo.png.
        /// </summary>
        public static string BasicLogoImageSource {
            get {
                return ResourceManager.GetString("BasicLogoImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bias Potential (V).
        /// </summary>
        public static string BiasPotential {
            get {
                return ResourceManager.GetString("BiasPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1:  Using the X and Y-Axis controls to the right, move the laser to the initial X and Y position of the spectrum..
        /// </summary>
        public static string BoundaryStep1 {
            get {
                return ResourceManager.GetString("BoundaryStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2:  Using the X and Y-Axis controls to the right, move the laser to the final X and Y position of the spectrum..
        /// </summary>
        public static string BoundaryStep2 {
            get {
                return ResourceManager.GetString("BoundaryStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3:  Using the controls to the right, set the movement step size to determine the number of rows and columns..
        /// </summary>
        public static string BoundaryStep3 {
            get {
                return ResourceManager.GetString("BoundaryStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Axis: {0:D}  Y-Axis: {1:D}  Z-Value: {2:E2}.
        /// </summary>
        public static string ChartPositionFormatString {
            get {
                return ResourceManager.GetString("ChartPositionFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart size.
        /// </summary>
        public static string ChartSize {
            get {
                return ResourceManager.GetString("ChartSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charts per page.
        /// </summary>
        public static string ChartsPerPage {
            get {
                return ResourceManager.GetString("ChartsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts to print.
        /// </summary>
        public static string ChartsToPrint {
            get {
                return ResourceManager.GetString("ChartsToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Wizard Results.
        /// </summary>
        public static string CheckWizardResults {
            get {
                return ResourceManager.GetString("CheckWizardResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the results of the Wizard below.  Click Back to change any of the properties.  Click Finish to close the Wizard and continue..
        /// </summary>
        public static string CheckWizardResultsDesc {
            get {
                return ResourceManager.GetString("CheckWizardResultsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Close32.png.
        /// </summary>
        public static string CloseImageSource {
            get {
                return ResourceManager.GetString("CloseImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the Active Spectrum.
        /// </summary>
        public static string CloseScreenTipDesc {
            get {
                return ResourceManager.GetString("CloseScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Acquisition.
        /// </summary>
        public static string ConfigureDAQ {
            get {
                return ResourceManager.GetString("ConfigureDAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Configure.png.
        /// </summary>
        public static string ConfigureDAQImageSource {
            get {
                return ResourceManager.GetString("ConfigureDAQImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the Data Acquisition card to accept photocurrent input.
        /// </summary>
        public static string ConfigureDAQScreenTipDesc {
            get {
                return ResourceManager.GetString("ConfigureDAQScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Mirrors.
        /// </summary>
        public static string ConfigureMirrors {
            get {
                return ResourceManager.GetString("ConfigureMirrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Mirrors.png.
        /// </summary>
        public static string ConfigureMirrorsImageSource {
            get {
                return ResourceManager.GetString("ConfigureMirrorsImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the Mirror raster movement.
        /// </summary>
        public static string ConfigureMirrorsScreenTipDesc {
            get {
                return ResourceManager.GetString("ConfigureMirrorsScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Laser Interface....
        /// </summary>
        public static string ConnectLaser {
            get {
                return ResourceManager.GetString("ConnectLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Mirror Interface....
        /// </summary>
        public static string ConnectMirror {
            get {
                return ResourceManager.GetString("ConnectMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Potentiostat Interface....
        /// </summary>
        public static string ConnectPotentiostat {
            get {
                return ResourceManager.GetString("ConnectPotentiostat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for the Dark Current to settle before the Spectrum scan begins.  Click Cancel to continue without waiting for the Dark Current to settle.  NOTE:  Canceling this step may result in poor data acquistion!.
        /// </summary>
        public static string CurrentSettleText {
            get {
                return ResourceManager.GetString("CurrentSettleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for Dark Current to Settle.
        /// </summary>
        public static string CurrentSettleTitle {
            get {
                return ResourceManager.GetString("CurrentSettleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAQ.
        /// </summary>
        public static string DAQ {
            get {
                return ResourceManager.GetString("DAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Current (μA):.
        /// </summary>
        public static string DarkCurrentTitle {
            get {
                return ResourceManager.GetString("DarkCurrentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Acquisition.
        /// </summary>
        public static string DataAcquistion {
            get {
                return ResourceManager.GetString("DataAcquistion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Export.
        /// </summary>
        public static string DataExport {
            get {
                return ResourceManager.GetString("DataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Not Found.
        /// </summary>
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not configure hardware at this time.
        /// </summary>
        public static string DoNotConfigure {
            get {
                return ResourceManager.GetString("DoNotConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter File Name.
        /// </summary>
        public static string EnterFileName {
            get {
                return ResourceManager.GetString("EnterFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the File to be used to store data and click Next..
        /// </summary>
        public static string EnterFileNameDesc {
            get {
                return ResourceManager.GetString("EnterFileNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Exit16.png.
        /// </summary>
        public static string ExitImageSourceSmall {
            get {
                return ResourceManager.GetString("ExitImageSourceSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the SHArK Application.
        /// </summary>
        public static string ExitScreenTipDesc {
            get {
                return ResourceManager.GetString("ExitScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Wizard is searching for hardware installed on your computer.  If a device is not installed properly, the Wizard will display &quot;Device Not Found.&quot;  You cannot license the SHArK application if you do not have the appropriate hardware installed on your computer.  .
        /// </summary>
        public static string HardwareDetectionText {
            get {
                return ResourceManager.GetString("HardwareDetectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A device to interface with the SHArK Hardware was not found or is not licensed.  Please check that all cables are connected and power is applied, then try again..
        /// </summary>
        public static string HardwareNotDetected {
            get {
                return ResourceManager.GetString("HardwareNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you plan to use this software only for data analysis purposes and not to operate hardware, check the box below and click Finish.  You may open this Wizard at any time to license it using the Configure button..
        /// </summary>
        public static string HardwareWizardDoNotConfigText {
            get {
                return ResourceManager.GetString("HardwareWizardDoNotConfigText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the Hardware Registration and Licensing..
        /// </summary>
        public static string HardwareWizardFinishDesc {
            get {
                return ResourceManager.GetString("HardwareWizardFinishDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!  You have successfully registered your hardware and configured your SHArK application to acquire data.  To begin using the SHArK application, click Finish to exit the Wizard..
        /// </summary>
        public static string HardwareWizardFinishText {
            get {
                return ResourceManager.GetString("HardwareWizardFinishText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish the Hardware Wizard.
        /// </summary>
        public static string HardwareWizardFinishTitle {
            get {
                return ResourceManager.GetString("HardwareWizardFinishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hardware installed on your computer is listed below.  If no hardware is listed, ensure that the equipment is properly connected and powered up and try this Wizard again.  Otherwise, click Next to continue..
        /// </summary>
        public static string HardwareWizardInstalledDesc {
            get {
                return ResourceManager.GetString("HardwareWizardInstalledDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed SHArK Hardware.
        /// </summary>
        public static string HardwareWizardInstalledTitle {
            get {
                return ResourceManager.GetString("HardwareWizardInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the SHArK application with the hardware that is installed, a valid license must be entered.  Enter the license key below and click Next to continue..
        /// </summary>
        public static string HardwareWizardLicenseDesc {
            get {
                return ResourceManager.GetString("HardwareWizardLicenseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter SHArK Application License.
        /// </summary>
        public static string HardwareWizardLicenseTitle {
            get {
                return ResourceManager.GetString("HardwareWizardLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hardwareWizard.
        /// </summary>
        public static string HardwareWizardName {
            get {
                return ResourceManager.GetString("HardwareWizardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Configuration Wizard.
        /// </summary>
        public static string HardwareWizardTitle {
            get {
                return ResourceManager.GetString("HardwareWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Wizard will help you configure your SHArK hardware to operate with this application.  .
        /// </summary>
        public static string HardwareWizardWelcomeDescription {
            get {
                return ResourceManager.GetString("HardwareWizardWelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to utilize the SHArK application, you must register the hardware and provide a software license.  To do this, connect all of the hardware cables to your computer and ensure that the hardware is powered on, then click Next to continue..
        /// </summary>
        public static string HardwareWizardWelcomeText {
            get {
                return ResourceManager.GetString("HardwareWizardWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Hardware Configuration Wizard.
        /// </summary>
        public static string HardwareWizardWelcomeTitle {
            get {
                return ResourceManager.GetString("HardwareWizardWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/SHArKLogo.png.
        /// </summary>
        public static string HomeButtonImageSource {
            get {
                return ResourceManager.GetString("HomeButtonImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Open, Save, and Print SHArK files..
        /// </summary>
        public static string HomeButtonTipDescription {
            get {
                return ResourceManager.GetString("HomeButtonTipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHArK Home Button.
        /// </summary>
        public static string HomeButtonTipHeader {
            get {
                return ResourceManager.GetString("HomeButtonTipHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Icons/SHArK.ico.
        /// </summary>
        public static string IconImageSource {
            get {
                return ResourceManager.GetString("IconImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Image File.
        /// </summary>
        public static string JPEG {
            get {
                return ResourceManager.GetString("JPEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/JPEGFile.png.
        /// </summary>
        public static string JPEGImageSource {
            get {
                return ResourceManager.GetString("JPEGImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Frequency (Hz).
        /// </summary>
        public static string LaserFrequency {
            get {
                return ResourceManager.GetString("LaserFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Interface:.
        /// </summary>
        public static string LaserName {
            get {
                return ResourceManager.GetString("LaserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser off delay (ms).
        /// </summary>
        public static string LaserOffDelay {
            get {
                return ResourceManager.GetString("LaserOffDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser on delay (ms).
        /// </summary>
        public static string LaserOnDelay {
            get {
                return ResourceManager.GetString("LaserOnDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Timing Constants.
        /// </summary>
        public static string LaserTiming {
            get {
                return ResourceManager.GetString("LaserTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the values below to determine the profile of the laser modulation and data collection.  If you do not know what values to use, use the defaults.  Click Next to continue..
        /// </summary>
        public static string LaserTimingDesc {
            get {
                return ResourceManager.GetString("LaserTimingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mdiRegion.
        /// </summary>
        public static string MdiRegion {
            get {
                return ResourceManager.GetString("MdiRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Movement Interface:.
        /// </summary>
        public static string MirrorName {
            get {
                return ResourceManager.GetString("MirrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirrors.
        /// </summary>
        public static string Mirrors {
            get {
                return ResourceManager.GetString("Mirrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        public static string Multiple {
            get {
                return ResourceManager.GetString("Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/New32.png.
        /// </summary>
        public static string NewImageSource {
            get {
                return ResourceManager.GetString("NewImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/New16.png.
        /// </summary>
        public static string NewImageSourceSmall {
            get {
                return ResourceManager.GetString("NewImageSourceSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Acquisition of a New Spectrum.
        /// </summary>
        public static string NewScreenTipDesc {
            get {
                return ResourceManager.GetString("NewScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newSpectrumWizard.
        /// </summary>
        public static string NewSpectrumWizardName {
            get {
                return ResourceManager.GetString("NewSpectrumWizardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Spectrum Wizard.
        /// </summary>
        public static string NewSpectrumWizardTitle {
            get {
                return ResourceManager.GetString("NewSpectrumWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of samples.
        /// </summary>
        public static string NumberOfSamples {
            get {
                return ResourceManager.GetString("NumberOfSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageOpenFile.
        /// </summary>
        public static string OpenFilePageName {
            get {
                return ResourceManager.GetString("OpenFilePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Open32.png.
        /// </summary>
        public static string OpenImageSource {
            get {
                return ResourceManager.GetString("OpenImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Open16.png.
        /// </summary>
        public static string OpenImageSourceSmall {
            get {
                return ResourceManager.GetString("OpenImageSourceSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an Existing SHArK Spectrum.
        /// </summary>
        public static string OpenScreenTipDesc {
            get {
                return ResourceManager.GetString("OpenScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open SHArK 3-D File.
        /// </summary>
        public static string OpenSHArKFile {
            get {
                return ResourceManager.GetString("OpenSHArKFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Final Position must to below and to the right of the Initial Position.  Move either Position and try again..
        /// </summary>
        public static string OutsideBoundary {
            get {
                return ResourceManager.GetString("OutsideBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Pause.png.
        /// </summary>
        public static string PauseImageSource {
            get {
                return ResourceManager.GetString("PauseImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause the active Spectrum data acquisition.
        /// </summary>
        public static string PauseScreenTipDesc {
            get {
                return ResourceManager.GetString("PauseScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potentiostat Interface:.
        /// </summary>
        public static string PotentiostatName {
            get {
                return ResourceManager.GetString("PotentiostatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potentiostat and Laser Properties.
        /// </summary>
        public static string PotstatLaserProperties {
            get {
                return ResourceManager.GetString("PotstatLaserProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the values of the Potentiostat bias and Laser modulation in the controls below.  Click Next to Continue..
        /// </summary>
        public static string PotstatLaserPropertiesDesc {
            get {
                return ResourceManager.GetString("PotstatLaserPropertiesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print all open windows.
        /// </summary>
        public static string PrintAll {
            get {
                return ResourceManager.GetString("PrintAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print current window only.
        /// </summary>
        public static string PrintCurrent {
            get {
                return ResourceManager.GetString("PrintCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Print32.png.
        /// </summary>
        public static string PrintImageSource {
            get {
                return ResourceManager.GetString("PrintImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Print16.png.
        /// </summary>
        public static string PrintImageSourceSmall {
            get {
                return ResourceManager.GetString("PrintImageSourceSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHArK Spectrum.
        /// </summary>
        public static string PrintJobName {
            get {
                return ResourceManager.GetString("PrintJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the Active Spectrum.
        /// </summary>
        public static string PrintScreenTipDesc {
            get {
                return ResourceManager.GetString("PrintScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing File Data to Chart....
        /// </summary>
        public static string ProcessingFileToChart {
            get {
                return ResourceManager.GetString("ProcessingFileToChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAW 3D File.
        /// </summary>
        public static string Raw3D {
            get {
                return ResourceManager.GetString("Raw3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Raw3D.png.
        /// </summary>
        public static string Raw3DImageSource {
            get {
                return ResourceManager.GetString("Raw3DImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading File....
        /// </summary>
        public static string ReadingFile {
            get {
                return ResourceManager.GetString("ReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting Initial Laser Position....
        /// </summary>
        public static string ResetInitialPosition {
            get {
                return ResourceManager.GetString("ResetInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Zoom.
        /// </summary>
        public static string ResetZoom {
            get {
                return ResourceManager.GetString("ResetZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/ResetZoom.png.
        /// </summary>
        public static string ResetZoomImageSource {
            get {
                return ResourceManager.GetString("ResetZoomImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out of the Spectrum completely.
        /// </summary>
        public static string ResetZoomScreenTipDesc {
            get {
                return ResourceManager.GetString("ResetZoomScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Restart.png.
        /// </summary>
        public static string RestartImageSource {
            get {
                return ResourceManager.GetString("RestartImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the paused Spectrum data acquisition.
        /// </summary>
        public static string RestartScreenTipDesc {
            get {
                return ResourceManager.GetString("RestartScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ribbonRegion.
        /// </summary>
        public static string RibbonRegion {
            get {
                return ResourceManager.GetString("RibbonRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainRibbon.
        /// </summary>
        public static string RibbonViewName {
            get {
                return ResourceManager.GetString("RibbonViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/SaveAs32.png.
        /// </summary>
        public static string SaveAsImageSource {
            get {
                return ResourceManager.GetString("SaveAsImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the Active Spectrum to a Different Format.
        /// </summary>
        public static string SaveAsScreenTipDesc {
            get {
                return ResourceManager.GetString("SaveAsScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Copy of Document As....
        /// </summary>
        public static string SaveAsSeparator {
            get {
                return ResourceManager.GetString("SaveAsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save SHArK 3-D File.
        /// </summary>
        public static string SaveSHArKFile {
            get {
                return ResourceManager.GetString("SaveSHArKFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale to IPCE.
        /// </summary>
        public static string ScaleToIPCE {
            get {
                return ResourceManager.GetString("ScaleToIPCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Scale.png.
        /// </summary>
        public static string ScaleToIPCEImageSource {
            get {
                return ResourceManager.GetString("ScaleToIPCEImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale the active Spectrum to Incident Photon to Current Efficiency.
        /// </summary>
        public static string ScaleToIPCEScreenTipDesc {
            get {
                return ResourceManager.GetString("ScaleToIPCEScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused:.
        /// </summary>
        public static string ScanPaused {
            get {
                return ResourceManager.GetString("ScanPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running:.
        /// </summary>
        public static string ScanRunning {
            get {
                return ResourceManager.GetString("ScanRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1:  Set the potential to apply to the electrode..
        /// </summary>
        public static string SetBiasPotential {
            get {
                return ResourceManager.GetString("SetBiasPotential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Initial Position.
        /// </summary>
        public static string SetInitialPosition {
            get {
                return ResourceManager.GetString("SetInitialPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2:  Enter the frequency at which the laser will be modulated in the text box to the right..
        /// </summary>
        public static string SetLaserFrequency {
            get {
                return ResourceManager.GetString("SetLaserFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4:  Set the ms to wait after turning the laser off prior to moving to the next point..
        /// </summary>
        public static string SetLaserOffDelay {
            get {
                return ResourceManager.GetString("SetLaserOffDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2:  Set the ms to wait after turning the laser on prior to acquiring data..
        /// </summary>
        public static string SetLaserOnDelay {
            get {
                return ResourceManager.GetString("SetLaserOnDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3:  Set the number of samples to acquire and average for each data point..
        /// </summary>
        public static string SetNumberSamples {
            get {
                return ResourceManager.GetString("SetNumberSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Spectrum Boundaries.
        /// </summary>
        public static string SetSpectrumBoundaries {
            get {
                return ResourceManager.GetString("SetSpectrumBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Controls to set the top left and bottom right points of the Spectrum.  Click Next to continue..
        /// </summary>
        public static string SetSpectrumBoundariesDesc {
            get {
                return ResourceManager.GetString("SetSpectrumBoundariesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pageSetBounds.
        /// </summary>
        public static string SetSpectrumBoundariesPageName {
            get {
                return ResourceManager.GetString("SetSpectrumBoundariesPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Up Chart....
        /// </summary>
        public static string SettingUpChart {
            get {
                return ResourceManager.GetString("SettingUpChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHArK.Common.
        /// </summary>
        public static string SHArKCommonName {
            get {
                return ResourceManager.GetString("SHArKCommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solar Hydrogen Activity Research Kit.
        /// </summary>
        public static string SHArKExpanded {
            get {
                return ResourceManager.GetString("SHArKExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE:  The Custom SHArK Electronics Box was detected as your potentiostat and laser interface.  Before clicking Finish on this Wizard, ensure that the + / - switch is set properly for the bias and that the laser switch is set to Pulsed..
        /// </summary>
        public static string SHArKHardwareWarning {
            get {
                return ResourceManager.GetString("SHArKHardwareWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainShellView.
        /// </summary>
        public static string ShellViewName {
            get {
                return ResourceManager.GetString("ShellViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Size.
        /// </summary>
        public static string StepSize {
            get {
                return ResourceManager.GetString("StepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Resources/Images/Stop.png.
        /// </summary>
        public static string StopImageSource {
            get {
                return ResourceManager.GetString("StopImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the active Spectrum data acquistion.
        /// </summary>
        public static string StopScreenTipDesc {
            get {
                return ResourceManager.GetString("StopScreenTipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabHost.
        /// </summary>
        public static string TabHostName {
            get {
                return ResourceManager.GetString("TabHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mainTabHost.
        /// </summary>
        public static string TabHostViewName {
            get {
                return ResourceManager.GetString("TabHostViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Current (μA):.
        /// </summary>
        public static string TargetCurrentTitle {
            get {
                return ResourceManager.GetString("TargetCurrentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string TitleSeparator {
            get {
                return ResourceManager.GetString("TitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Axis.
        /// </summary>
        public static string XAxis {
            get {
                return ResourceManager.GetString("XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X / Y-Position.
        /// </summary>
        public static string XYPosition {
            get {
                return ResourceManager.GetString("XYPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Axis.
        /// </summary>
        public static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
    }
}
